### ISSUE TITLE
Tigerseye crashes servers with Lithium installed

### ISSUE THREAD

**Issue by CammiePone** [williewillus/botania-fabric-issues#95]
```
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 10/17/21, 4:36 PM
Description: Ticking block entity

java.lang.IllegalStateException: Cannot add sublisteners after listening range was set!
	at me.jellysquid.mods.lithium.common.entity.tracker.nearby.NearbyEntityListenerMulti.addListener(NearbyEntityListenerMulti.java:19)
	at net.minecraft.class_1297.addListener(class_1297.java:3991)
	at net.minecraft.class_1338.handler$zbi000$init(class_1338.java:543)
	at net.minecraft.class_1338.<init>(class_1338.java:44)
	at net.minecraft.class_1338.<init>(class_1338.java:29)
	at vazkii.botania.common.block.subtile.functional.SubTileTigerseye.tickFlower(SubTileTigerseye.java:62)
	at vazkii.botania.api.subtile.TileEntitySpecialFlower.commonTick(TileEntitySpecialFlower.java:107)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:886)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:941)
	at net.minecraft.class_1937.method_18471(class_1937.java:474)
	at net.minecraft.class_3218.method_18765(class_3218.java:422)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891)
	at net.minecraft.class_3176.method_3813(class_3176.java:335)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at me.jellysquid.mods.lithium.common.entity.tracker.nearby.NearbyEntityListenerMulti.addListener(NearbyEntityListenerMulti.java:19)
	at net.minecraft.class_1297.addListener(class_1297.java:3991)
	at net.minecraft.class_1338.handler$zbi000$init(class_1338.java:543)
	at net.minecraft.class_1338.<init>(class_1338.java:44)
	at net.minecraft.class_1338.<init>(class_1338.java:29)
	at vazkii.botania.common.block.subtile.functional.SubTileTigerseye.tickFlower(SubTileTigerseye.java:62)
	at vazkii.botania.api.subtile.TileEntitySpecialFlower.commonTick(TileEntitySpecialFlower.java:107)

-- Block entity being ticked --
Details:
	Name: botania:tigerseye // vazkii.botania.common.block.subtile.functional.SubTileTigerseye
	Block: Block{botania:tigerseye}
	Block location: World: (48,64,-757), Section: (at 0,0,11 in 3,4,-48; chunk contains blocks 48,0,-768 to 63,255,-753), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,0,-1024 to 511,255,-513)
	Block: Block{botania:tigerseye}
	Block location: World: (48,64,-757), Section: (at 0,0,11 in 3,4,-48; chunk contains blocks 48,0,-768 to 63,255,-753), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,0,-1024 to 511,255,-513)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:886)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:941)
	at net.minecraft.class_1937.method_18471(class_1937.java:474)
	at net.minecraft.class_3218.method_18765(class_3218.java:422)

-- Affected level --
Details:
	All players: 1 total; [class_3222['MoriyaShiine'/137, l='ServerLevel[world]', x=45.89, y=64.00, z=-756.35]]
	Chunk stats: 2864
	Level dimension: minecraft:overworld
	Level spawn location: World: (128,67,-80), Section: (at 0,3,0 in 8,4,-5; chunk contains blocks 128,0,-80 to 143,255,-65), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 32893085 game time, 36272098 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 35781 (now: false), thunder time: 45621 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891)
	at net.minecraft.class_3176.method_3813(class_3176.java:335)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (amd64) version 5.14.9-zen2-1-zen
	Java Version: 16.0.2, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4137410144 bytes (3945 MiB) / 8589934592 bytes (8192 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3700X 8-Core Processor
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 258.00
	Graphics card #0 deviceId: 0x731f
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 28292.27
	Virtual memory used (MB): 21363.82
	Swap memory total (MB): 12288.00
	Swap memory used (MB): 4.50
	JVM Flags: 2 total; -Xmx8G -Xms8G
	Fabric Mods: 
		architectury: Architectury 2.5.32
		blue_endless_jankson: jankson 1.2.1
		botania: Botania 1.17.1-420-FABRIC-SNAPSHOT
		cardinal-components-base: Cardinal Components API (base) 3.0.0
		cardinal-components-block: Cardinal Components API (blocks) 3.0.0
		cardinal-components-entity: Cardinal Components API (entities) 3.0.0
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v5 5.0.38
		dual_riders: DualRiders 1.0.5
		fabric: Fabric API 0.40.8+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446318
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931818
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+cbda931818
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931818
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931818
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.3+87cc6e4c18
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.10+fc40aa9d18
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931818
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+cbda931818
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+cbda931818
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+cbda931818
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.11+7931163218
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4658223018
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931818
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.4.0+7931163218
		fabricloader: Fabric Loader 0.11.6
		fiber: fiber 0.23.0-2
		inventorysorter: Inventory Sorter 1.8.0-1.17
		java: OpenJDK 64-Bit Server VM 16
		kyrptconfig: Kytpt Config 1.1.10-1.17
		lithium: Lithium 0.7.4
		minecraft: Minecraft 1.17.1
		patchouli: Patchouli 1.17.1-56-FABRIC
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		respawnablepets: Respawnable Pets 1.17-5
		roughlyenoughitems: Roughly Enough Items 6.0.287-alpha
		starlight: Starlight 1.0.0+fabric.73f6d37
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		trinkets: Trinkets 3.0.4
	Player Count: 1 / 20; [class_3222['MoriyaShiine'/137, l='ServerLevel[world]', x=45.89, y=64.00, z=-756.35]]
	Data Packs: vanilla, Fabric Mods
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

**Comment by Hubry** [comment]
We can either try fixing it properly, or we can just tell Lithium we want `mixin.ai.nearby_entity_tracking` disabled I guess, but that would be a bit of a loss...

**Comment by Hubry** [comment]
https://github.com/VazkiiMods/Botania/commit/5dc3379a115818f177643fbce6899a492241b10c, two birds with one stone
